apiVersion: v1
kind: Secret
metadata:
  name: risa-imap-credentials
  namespace: risa
type: Opaque
stringData:
  IMAP_HOST: "cslewis.phaedo.com"
  IMAP_PORT: "993"
  IMAP_USER: "rquick"
  IMAP_PASS: "REPLACE_ME"
